### ISSUE TITLE
Integrate Sequelize and postgresql

### ISSUE THREAD

**Issue by ilakshmikanthp** [pankod/moleculerjs-boilerplate#53]
I want to integrate sequelize ORM in my project in place of TypeORM and also postgresql. Can I get support for it or if possible can I get any boilerplate for it.

**Comment by BatuhanW** [comment]
This boilerplate had Sequelize before, here is the commit where we migrated to TypeORM, you can take a look and do reverse migration;

https://github.com/pankod/moleculerjs-boilerplate/commit/40580c6c5edd512e2155b7f1ff5d1716a05e4d10
