### ISSUE TITLE
Any intention to upgrade this boilerplate to support the moleculer v0.14?

### ISSUE THREAD

**Issue by austinrivas** [pankod/moleculerjs-boilerplate#65]
Really great project, drew a lot of inspiration from it that I am pulling into an existing moleculer project.

I did notice however that the current project is not compatible with moleculer v0.14.

Notably the class declarations for services.

Is there any intention to keep this boilerplate up to date?

**Comment by austinrivas** [comment]
I've done the upgrade, would you like a PR?

**Comment by omeraplak** [comment]
@austinrivas Hello,
We're glad we heard that. We are waiting your PR! 🎉

**Comment by austinrivas** [comment]
Awesome, I'll have it up in a day or two.
